In [7]:
import numpy as np
import math
from scipy.stats import norm, chi2, chi2_contingency
from IPython.display import display, Markdown

1. State the Hypotheses

Null Hypothesis (H
0
​
 ): There is no significant association (independence) between the type of device purchased and customer satisfaction.

Alternative Hypothesis (H
a
​
 ): There is a significant association (dependence) between the type of device purchased and customer satisfaction.

In [8]:
#  Data and Parameters
# Observed Frequencies (O) - Contingency Table
OBSERVED_O = np.array([
    [50, 70],  # Very Satisfied
    [80, 100], # Satisfied
    [60, 90],  # Neutral
    [30, 50],  # Unsatisfied
    [20, 50]   # Very Unsatisfied
])
ALPHA_CHI2 = 0.05 # Significance level

#  1. State the Hypotheses
print("1. State the Hypotheses:")
print("   Null Hypothesis (H₀): Device type and satisfaction are independent (No association).")
print("   Alternative Hypothesis (Hₐ): Device type and satisfaction are dependent (Significant association).")


1. State the Hypotheses:
   Null Hypothesis (H₀): Device type and satisfaction are independent (No association).
   Alternative Hypothesis (Hₐ): Device type and satisfaction are dependent (Significant association).


## 2. Compute the Chi-Square Statistic

The observed data ($O$) is the contingency table. The total number of customers is 600.

| Satisfaction | Smart Thermostat (O) | Smart Light (O) | Row Total |
| :--- | :--- | :--- | :--- |
| Very Satisfied | 50 | 70 | 120 |
| Satisfied | 80 | 100 | 180 |
| Neutral | 60 | 90 | 150 |
| Unsatisfied | 30 | 50 | 80 |
| Very Unsatisfied | 20 | 50 | 70 |
| **Col. Total** | 240 | 360 | 600 |

$$
\text{Expected Frequencies (E): } \quad E = \frac{(\text{Row Total}) \times (\text{Column Total})}{\text{Grand Total}}
$$

The matrix of Expected Frequencies ($E$) is:
$$
\begin{pmatrix} 48 & 72 \\ 72 & 108 \\ 60 & 90 \\ 32 & 48 \\ 28 & 42 \end{pmatrix}
$$

$$\text{Chi-Square Statistic ($\chi^2$):} \quad \chi^2 = \sum \frac{(O - E)^2}{E}$$

$$\chi^2 \approx \frac{(50-48)^2}{48} + \dots + \frac{(50-42)^2}{42} \approx \mathbf{5.6382}$$

In [9]:
#  2. Compute the Chi-Square Statistic (χ²)
CHI2_STATISTIC, P_VALUE, DF_CHI2, EXPECTED_E = chi2_contingency(OBSERVED_O)

print("2. Compute the Chi-Square Statistic (χ²):")
display(Markdown(f"Formula: $$\\chi^2 = \\sum \\frac{{(O - E)^2}}{{E}}$$"))
print(f"   Degrees of Freedom (df): {DF_CHI2} (df = (5-1) * (2-1) = 4)")
print(f"   Calculated Chi-Square Statistic (χ²): {CHI2_STATISTIC:.4f}")



2. Compute the Chi-Square Statistic (χ²):


Formula: $$\chi^2 = \sum \frac{(O - E)^2}{E}$$

   Degrees of Freedom (df): 4 (df = (5-1) * (2-1) = 4)
   Calculated Chi-Square Statistic (χ²): 5.6382


3. Determine the Critical Value

Degrees of Freedom (df): df=(Rows−1)×(Columns−1)=(5−1)×(2−1)=4.


Critical Value (χ
crit
2
​
 ): For α=0.05 and df=4.


χ
crit
2
​
 =9.488

In [10]:
#  3. Determine the Critical Value
CRITICAL_VALUE_CHI2 = chi2.ppf(1 - ALPHA_CHI2, DF_CHI2)

print("3. Critical Value Determination:")
print(f"   Critical Value (χ²_crit): {CRITICAL_VALUE_CHI2:.4f}")



3. Critical Value Determination:
   Critical Value (χ²_crit): 9.4877


4. Make a Decision

Since the calculated Chi-Square statistic (χ
2
 =5.6382) is less than the critical value (χ
crit
2
​
 =9.488), we Fail to Reject the Null Hypothesis (H
0
​
 ).

In [12]:
# 4. Make a Decision & 5. Conclusion
DECISION_2 = "Fail to Reject H₀" if CHI2_STATISTIC <= CRITICAL_VALUE_CHI2 else "Reject H₀"

print("4. Decision and 5. Conclusion:")
print(f"   Decision: {DECISION_2} (Since {CHI2_STATISTIC:.4f} ≤ {CRITICAL_VALUE_CHI2:.4f})")
print(f"   Conclusion: We {DECISION_2.lower()}. There is **no statistically significant evidence** to conclude that there is an association between the type of device and the customer's satisfaction level[cite: 10].")


4. Decision and 5. Conclusion:
   Decision: Fail to Reject H₀ (Since 5.6382 ≤ 9.4877)
   Conclusion: We fail to reject h₀. There is **no statistically significant evidence** to conclude that there is an association between the type of device and the customer's satisfaction level[cite: 10].


5. Conclusion

There is no statistically significant evidence at the α=0.05 level to conclude that there is an association between the type of smart home device purchased and the customer's satisfaction level.